# Generated by Django 3.2.9 on 2021-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chartsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('chartset', models.ManyToManyField(to='chartsets.Chartset', verbose_name='Проект')),
            ],
        ),
    ]
