# Generated by Django 3.2.9 on 2021-11-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartsets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
